"""Parse requirements for kconfiglib version and write kconfig/private/kconfiglib_version.bzl."""

import argparse
import base64
import binascii
import logging
import os
import platform
import re
import sys
from pathlib import Path

KCONFIGLIB_PACKAGE = "kconfiglib"
VERSION_REGEX = re.compile(r"^kconfiglib==(\d+\.\d+(?:\.\d+)?)\s*(?:\\)?\s*$")
HASH_REGEX = re.compile(r"--hash=sha256:([a-fA-F0-9]+)")
URL_REGEX = re.compile(r"#\s*(https://[^\s#]+?)(?:#sha256=|\s|$)")

PLATFORM_MAP = [
    (("Darwin", "arm64"), "macos_aarch64"),
    (("Darwin", "x86_64"), "macos_aarch64"),  # fallback; no macos_x86_64 file
    (("Linux", "x86_64"), "linux_x86_64"),
    (("Linux", "aarch64"), "linux_aarch64"),
    (("Linux", "arm64"), "linux_aarch64"),
    (("Windows", "AMD64"), "windows_x86_64"),
    (("Windows", "x86_64"), "windows_x86_64"),
]

BZL_TEMPLATE = '''"""kconfiglib version info

AUTOGENERATED: DO NOT MODIFY

To regenerate:

    bazel run //tools/update_version

"""

VERSION_INFO = {{
    "urls": {urls},
    "integrity": "{integrity}",
    "strip_prefix": "{strip_prefix}",
    "version": "{version}",
}}
'''


def _workspace_root() -> Path:
    if "BUILD_WORKSPACE_DIRECTORY" in os.environ:
        return Path(os.environ["BUILD_WORKSPACE_DIRECTORY"])
    return Path(__file__).resolve().parent.parent.parent


def _host_platform() -> str:
    """Return requirements file platform suffix (e.g. macos_aarch64) for current host."""
    system = platform.system()
    machine = platform.machine()
    for (os_name, arch), platform_key in PLATFORM_MAP:
        if system == os_name and machine == arch:
            return platform_key
    return "macos_aarch64"  # default fallback


def _default_requirements_path(root: Path) -> Path:
    return root / "tools" / "requirements" / f"requirements_{_host_platform()}.txt"


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    root = _workspace_root()
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "kconfig" / "private" / "kconfiglib_version.bzl",
        help="Path to write kconfiglib_version.bzl.",
    )
    parser.add_argument(
        "--requirements",
        type=Path,
        default=None,
        help="Path to requirements*.txt; default is host-based under tools/requirements.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose logging",
    )
    return parser.parse_args()


def integrity(hex_str: str) -> str:
    """Convert a sha256 hex value to a Bazel integrity value (sha256-<base64>)."""
    try:
        raw_bytes = binascii.unhexlify(hex_str.strip())
    except binascii.Error as e:
        raise ValueError(f"Invalid hex input: {e}") from e
    encoded = base64.b64encode(raw_bytes).decode("utf-8")
    return f"sha256-{encoded}"


def parse_kconfiglib_from_requirements(content: str) -> dict[str, object]:
    """Extract version, hash, and url for kconfiglib from requirements file content."""
    lines = content.splitlines()
    version = None
    hash_hex = None
    url = None
    i = 0
    while i < len(lines):
        line = lines[i]
        match = VERSION_REGEX.match(line.strip())
        if match:
            version = match.group(1)
            # Consume continuation lines (indented or part of same block)
            j = i + 1
            while j < len(lines):
                next_line = lines[j]
                # Stop at next top-level package: non-empty line not starting with whitespace
                if next_line.strip() and not (
                    next_line.startswith(" ") or next_line.startswith("\t")
                ):
                    break
                if not next_line.strip():
                    j += 1
                    continue
                hash_m = HASH_REGEX.search(next_line)
                if hash_m:
                    hash_hex = hash_m.group(1)
                if "# https://" in next_line and "kconfiglib" in next_line:
                    url_m = URL_REGEX.search(next_line)
                    if url_m:
                        url = url_m.group(1).strip()
                j += 1
            break
        i += 1
    if version is None:
        return {}
    result: dict[str, object] = {"version": version, "integrity": "", "urls": []}
    if hash_hex:
        result["integrity"] = integrity(hash_hex)
    if url:
        result["urls"] = [url]
    return result


def main() -> None:
    """Update kconfiglib_version.bzl from the pinned requirements file."""
    args = parse_args()
    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    root = _workspace_root()
    req_path = (
        args.requirements
        if args.requirements is not None
        else _default_requirements_path(root)
    )
    if not req_path.is_absolute():
        req_path = root / req_path
    if not req_path.exists():
        logging.error("Requirements file not found: %s", req_path)
        sys.exit(1)

    content = req_path.read_text(encoding="utf-8")
    info = parse_kconfiglib_from_requirements(content)
    if not info:
        logging.error("kconfiglib not found in %s", req_path)
        sys.exit(1)

    # Format urls for Starlark: ["url1", "url2"]
    urls_str = repr(info.get("urls", []))
    integrity_str = info.get("integrity", "")
    strip_prefix_str = ""
    version_str = info.get("version", "")

    out_content = BZL_TEMPLATE.format(
        urls=urls_str,
        integrity=integrity_str,
        strip_prefix=strip_prefix_str,
        version=version_str,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(out_content, encoding="utf-8")
    logging.info("Wrote %s (version=%s)", args.output, version_str)


if __name__ == "__main__":
    main()
