"""kconfiglib version info

AUTOGENERATED: DO NOT MODIFY

To regenerate:

    bazel run //tools/update_version

"""

VERSION_INFO = {
    "integrity": "sha256-7c01og5+E4qanpYUkCf4BfeF6BjS6uQAtvqLDIhFEUo=",
    "strip_prefix": "",
    "urls": ["https://files.pythonhosted.org/packages/8a/f1/d98a89231e779b079b977590efcc31249d959c8f1d4b5858cad69695ff9c/kconfiglib-14.1.0-py2.py3-none-any.whl"],
    "version": "14.1.0",
}
