"""Generate a defs.bzl that overlays .config values onto an existing kconfig repository.

This script is invoked by the ``kconfig_overrides_repository`` rule.
It produces a ``defs.bzl`` containing the original/override data dicts
then delegates transition and rule creation to
``@rules_kconfig//kconfig/private:kconfig_override_utils.bzl``.
"""

import argparse
import json
import logging
from pathlib import Path
from typing import Union

from kconfig.private.kconfig_parser import (
    collect_settings,
    parse_kconfig,
    read_source_files,
)

log = logging.getLogger(__name__)

_DEFS_TEMPLATE = """\
\"\"\"Generated by rules_kconfig. DO NOT EDIT.\"\"\"

load("@rules_kconfig//kconfig/private:kconfig_override_utils.bzl", "make_kconfig_override_transition", "make_kconfig_overrides_rules")

_ORIGINAL_DEFAULTS = {{
{original_defaults}}}

_OVERRIDES = {{
{overrides}}}

_kconfig_overrides_transition = make_kconfig_override_transition(_ORIGINAL_DEFAULTS, _OVERRIDES)

_with_kconfig_overrides, _with_kconfig_overrides_binary = make_kconfig_overrides_rules(_kconfig_overrides_transition)

def with_kconfig_overrides(name, actual, executable = False, **kwargs):
    \"\"\"Apply .config overrides to a kconfig-dependent target via a transition.

    Args:
        name: Target name.
        actual: The kconfig-dependent target to apply overrides to.
        executable: Set to True when wrapping an executable target (e.g. cc_binary).
        **kwargs: Additional attributes forwarded to the underlying rule.
    \"\"\"
    if executable:
        _with_kconfig_overrides_binary(name = name, actual = actual, **kwargs)
    else:
        _with_kconfig_overrides(name = name, actual = actual, **kwargs)
"""

_BUILD_TEMPLATE_HEADER = """\
# Generated by rules_kconfig. DO NOT EDIT.

load("//:defs.bzl", "with_kconfig_overrides")
"""

_BUILD_TEMPLATE_EXPORTS = """\
exports_files(["rendered.config"])
"""

_BUILD_TEMPLATE_BODY = """\
with_kconfig_overrides(
    name = "config",
    actual = "{kconfig_repo}//:config",
    visibility = ["//visibility:public"],
)

alias(
    name = "lib",
    actual = "{kconfig_repo}//:lib",
    visibility = ["//visibility:public"],
)
"""

_MENUCONFIG_TEMPLATE = """\
load("@rules_kconfig//kconfig:menuconfig.bzl", "menuconfig")

menuconfig(
    name = "menuconfig",
    config = "{config_ws_path}",
    kconfig = "//:lib",
    visibility = ["//visibility:public"],
)
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--kconfig",
        type=Path,
        required=True,
        help="Path to the root Kconfig file (inside kconfig_srcs/).",
    )
    parser.add_argument(
        "--srctree",
        type=Path,
        required=True,
        help="Path to the kconfig_srcs/ directory.",
    )
    parser.add_argument(
        "--config",
        type=Path,
        required=True,
        help="Path to the .config file with override values.",
    )
    parser.add_argument(
        "--base_config",
        type=Path,
        default=None,
        help="Path to the base rendered .config from the source kconfig repository.",
    )
    parser.add_argument(
        "--kconfig_repo",
        type=str,
        required=True,
        help="Canonical repo prefix of the source kconfig repository (e.g. '@@rules_kconfig++kconfig+ext_kconfig').",
    )
    parser.add_argument(
        "--out_defs",
        type=Path,
        required=True,
        help="Output path for the generated defs.bzl.",
    )
    parser.add_argument(
        "--out_build",
        type=Path,
        required=True,
        help="Output path for the generated BUILD.bazel.",
    )
    parser.add_argument(
        "--config_ws_path",
        type=str,
        required=True,
        help=        "Workspace-relative path to the .config file (for the generated menuconfig target).",
    )
    parser.add_argument(
        "--out_rendered_config",
        type=Path,
        default=None,
        help="Output path for the fully resolved .config file.",
    )
    parser.add_argument(
        "--settings_labels",
        type=str,
        default="{}",
        help="JSON-encoded dict of CONFIG_* names with user-provided labels (skipped in transitions).",
    )
    parser.add_argument("--verbose", action="store_true", help="Enable verbose logging")
    return parser.parse_args()


def _starlark_literal(val: Union[bool, int, str]) -> str:
    """Format a Python value as a Starlark literal."""
    if isinstance(val, bool):
        return "True" if val else "False"
    if isinstance(val, int):
        return str(val)
    escaped = val.replace("\\", "\\\\").replace('"', '\\"')
    return '"{}"'.format(escaped)


def _render_dict_entries(entries: dict[str, str]) -> str:
    """Render sorted dict entries as indented Starlark key-value lines."""
    lines = []
    for label, val in sorted(entries.items()):
        lines.append('    "{}": {},'.format(label, val))
    return "\n".join(lines)


def _render_defs(
    original_defaults: dict[str, str],
    overrides: dict[str, str],
) -> str:
    """Render the defs.bzl file from the template."""
    return _DEFS_TEMPLATE.format(
        original_defaults=_render_dict_entries(original_defaults),
        overrides=_render_dict_entries(overrides),
    )


def main() -> None:
    args = parse_args()

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO)

    kconfig_path = args.kconfig.absolute()
    srctree = args.srctree.absolute()
    config_path = args.config.absolute()

    log.info("Parsing %s (srctree=%s)", kconfig_path, srctree)
    kconf = parse_kconfig(kconfig_path, srctree)

    has_base_config = args.base_config is not None
    if has_base_config:
        base_config_path = args.base_config.absolute()
        log.info("Loading base config from %s", base_config_path)
        kconf.load_config(str(base_config_path))

    source_cache = read_source_files(kconf, srctree)
    original_settings = collect_settings(kconf, source_cache, has_defaults=has_base_config)

    labeled: set[str] = set(json.loads(args.settings_labels))

    original_defaults: dict[str, str] = {}
    for s in original_settings:
        if f"CONFIG_{s.name}" in labeled:
            continue
        flag_label = "{repo}//:CONFIG_{name}".format(repo=args.kconfig_repo, name=s.name)
        original_defaults[flag_label] = _starlark_literal(s.default)

    log.info("Loading overrides from %s", config_path)
    kconf.load_config(str(config_path))

    override_settings = collect_settings(kconf, source_cache, has_defaults=True)

    overrides: dict[str, str] = {}
    override_by_name = {s.name: s for s in override_settings}
    for s in original_settings:
        if f"CONFIG_{s.name}" in labeled:
            continue
        override_s = override_by_name.get(s.name)
        if override_s and override_s.default != s.default:
            flag_label = "{repo}//:CONFIG_{name}".format(repo=args.kconfig_repo, name=s.name)
            overrides[flag_label] = _starlark_literal(override_s.default)

    args.out_defs.write_text(_render_defs(original_defaults, overrides), encoding="utf-8")

    if args.out_rendered_config:
        kconf.write_config(str(args.out_rendered_config))

    build_content = _BUILD_TEMPLATE_HEADER
    if args.out_rendered_config:
        build_content += "\n" + _BUILD_TEMPLATE_EXPORTS
    build_content += "\n" + _BUILD_TEMPLATE_BODY.format(kconfig_repo=args.kconfig_repo)
    build_content += "\n"
    build_content += _MENUCONFIG_TEMPLATE.format(config_ws_path=args.config_ws_path)

    args.out_build.write_text(build_content, encoding="utf-8")


if __name__ == "__main__":
    main()
