"""A script for parsing kconfig files and rendering the equivalent to a Bazel repository"""

import argparse
import dataclasses
import logging
import os
from pathlib import Path, PurePosixPath
from typing import Union

import kconfiglib

_TYPE_MAP = {
    kconfiglib.BOOL: "bool_flag",
    kconfiglib.TRISTATE: "string_flag",
    kconfiglib.INT: "int_flag",
    kconfiglib.HEX: "string_flag",
    kconfiglib.STRING: "string_flag",
}

_FALSEY_PYTHON_DEFAULTS: dict[str, Union[bool, int, str]] = {
    "bool_flag": False,
    "int_flag": 0,
    "string_flag": "",
}

_KCONFIG_BLOCK_STARTERS = frozenset(
    {
        "config",
        "menuconfig",
        "menu",
        "endmenu",
        "choice",
        "endchoice",
        "comment",
        "source",
        "rsource",
        "osource",
        "orsource",
        "if",
        "endif",
        "mainmenu",
    }
)

_BUILD_HEADER_TEMPLATE = """\
load("@bazel_skylib//rules:common_settings.bzl", {rules})
"""

_FLAG_TEMPLATE = """\
{rule}(
    name = "CONFIG_{name}",
    build_setting_default = {default},
    visibility = ["//visibility:public"],
)
"""

_AUTOCONF_TEMPLATE = """\
load("@rules_kconfig//kconfig/private:kconfig_autoconf.bzl", "kconfig_autoconf")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc_autoconf//autoconf:autoconf_hdr.bzl", "autoconf_hdr")

kconfig_autoconf(
    name = "autoconf",
    settings = [
{settings}
    ],
    visibility = ["//visibility:public"],
)

autoconf_hdr(
    name = "config_h",
    out = "config.h",
    template = "config.h.in",
    deps = [":autoconf"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "config",
    hdrs = ["config.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
)
"""

_CONFIG_H_IN_TEMPLATE = """\
/* Generated by rules_kconfig. DO NOT EDIT. */

{undefs}
"""

log = logging.getLogger(__name__)


@dataclasses.dataclass(frozen=True)
class KconfigSetting:
    """A parsed Kconfig symbol mapped to its Bazel build setting representation."""

    name: str
    """Symbol name without the CONFIG_ prefix, e.g. ``"FOO"``."""

    rule: str
    """Bazel rule kind: ``"bool_flag"``, ``"int_flag"``, or ``"string_flag"``."""

    default: Union[bool, int, str]
    """Python-native default value for the build setting."""


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument(
        "--config", type=Path, required=True, help="The path to the kconfig file."
    )
    parser.add_argument(
        "--out_build",
        type=Path,
        required=True,
        help="The output location of the `BUILD.bazel` file.",
    )
    parser.add_argument(
        "--out_manifest",
        type=Path,
        required=True,
        help="The output location of the `kconfig.manifest` file.",
    )
    parser.add_argument(
        "--out_config_h_in",
        type=Path,
        required=True,
        help="The output location of the `config.h.in` template file.",
    )
    parser.add_argument(
        "--srctree",
        type=Path,
        default=None,
        help="The root of the source tree. Defaults to the parent of --config.",
    )
    parser.add_argument("--verbose", action="store_true", help="Enable verbose logging")

    return parser.parse_args()


def read_source_files(kconf: kconfiglib.Kconfig, srctree: Path) -> dict[str, list[str]]:
    """Read and cache all Kconfig source files, keyed by kconfiglib filename."""
    cache: dict[str, list[str]] = {}
    for filename in kconf.kconfig_filenames:
        abs_path = Path(filename)
        if not abs_path.is_absolute():
            abs_path = srctree / filename
        try:
            cache[filename] = (
                abs_path.resolve().read_text(encoding="utf-8").splitlines()
            )
        except OSError:
            log.warning("Could not read Kconfig source: %s", abs_path)
    return cache


def _is_shell_tainted(
    sym: kconfiglib.Symbol, source_cache: dict[str, list[str]]
) -> bool:
    """Check whether any definition of sym directly contains $(shell,...) macros."""
    for node in sym.nodes:
        lines = source_cache.get(node.filename)
        if lines is None:
            continue

        start = node.linenr - 1
        end = start + 1
        while end < len(lines):
            line = lines[end]
            stripped = line.lstrip()
            if not stripped or stripped.startswith("#"):
                end += 1
                continue
            if line[0] not in (" ", "\t"):
                first_word = stripped.split()[0]
                if first_word in _KCONFIG_BLOCK_STARTERS:
                    break
            end += 1

        if any("$(shell," in lines[i] for i in range(start, min(end, len(lines)))):
            return True

    return False


def _python_default(sym: kconfiglib.Symbol, rule: str) -> Union[bool, int, str]:
    """Convert a symbol's resolved Kconfig default to a Python-native value."""
    if rule == "bool_flag":
        return sym.str_value == "y"
    if rule == "int_flag":
        try:
            return int(sym.str_value)
        except ValueError:
            return 0
    return sym.str_value


def collect_settings(
    kconf: kconfiglib.Kconfig,
    source_cache: dict[str, list[str]],
) -> list[KconfigSetting]:
    """Parse a Kconfig object into a list of :class:`KconfigSetting` entries.

    Symbols whose definitions contain ``$(shell,...)`` macros receive the
    falsey default for their type to avoid host-dependent values.
    """
    result: list[KconfigSetting] = []
    for sym in kconf.unique_defined_syms:
        rule = _TYPE_MAP.get(sym.orig_type)
        if not rule:
            log.debug("Skipping symbol %s (type %s)", sym.name, sym.orig_type)
            continue

        if _is_shell_tainted(sym, source_cache):
            default = _FALSEY_PYTHON_DEFAULTS[rule]
            log.info("CONFIG_%s uses $(shell,...); defaulting to %s", sym.name, default)
        else:
            default = _python_default(sym, rule)

        result.append(KconfigSetting(name=sym.name, rule=rule, default=default))
    return result


def _starlark_default(setting: KconfigSetting) -> str:
    """Format a :class:`KconfigSetting` default as a Starlark literal."""
    val = setting.default
    if isinstance(val, bool):
        return "True" if val else "False"
    if isinstance(val, int):
        return str(val)
    escaped = val.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _render_build_file(settings: list[KconfigSetting]) -> str:
    """Render a BUILD.bazel file with build settings for each Kconfig symbol."""
    if not settings:
        return "# No Kconfig symbols found.\n"

    needed_rules = sorted({s.rule for s in settings})
    parts = [
        _BUILD_HEADER_TEMPLATE.format(
            rules=", ".join(f'"{r}"' for r in needed_rules),
        )
    ]

    for s in settings:
        parts.append("")
        parts.append(
            _FLAG_TEMPLATE.format(
                rule=s.rule,
                name=s.name,
                default=_starlark_default(s),
            )
        )

    settings_str = "\n".join(f'        ":CONFIG_{s.name}",' for s in settings)
    parts.append("")
    parts.append(_AUTOCONF_TEMPLATE.format(settings=settings_str))

    return "".join(parts)


def _render_config_h_in(settings: list[KconfigSetting]) -> str:
    """Render a config.h.in template with #undef for each Kconfig symbol."""
    undefs = "\n".join(f"#undef CONFIG_{s.name}" for s in settings)
    return _CONFIG_H_IN_TEMPLATE.format(undefs=undefs)


def _render_manifest(kconf: kconfiglib.Kconfig, srctree: Path) -> str:
    """Render a manifest of all Kconfig files visited during parsing."""
    lines = []
    for filename in kconf.kconfig_filenames:
        abs_path = Path(filename)
        if not abs_path.is_absolute():
            abs_path = srctree / filename
        rel = abs_path.resolve().relative_to(srctree.resolve())
        lines.append(str(PurePosixPath(rel)))
    return "\n".join(lines) + "\n" if lines else ""


def main() -> None:
    """The main entrypoint"""
    args = parse_args()

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO)

    config: Path = args.config.resolve()
    srctree: Path = (args.srctree or config.parent).resolve()

    log.info("Parsing %s (srctree=%s)", config, srctree)

    prev_dir = os.getcwd()
    os.chdir(srctree)
    try:
        os.environ["srctree"] = str(srctree)
        kconf = kconfiglib.Kconfig(
            filename=str(config),
            warn=False,
            warn_to_stderr=False,
        )
    finally:
        os.chdir(prev_dir)

    log.info(
        "Parsed %d unique symbols from %d files",
        len(kconf.unique_defined_syms),
        len(kconf.kconfig_filenames),
    )

    source_cache = read_source_files(kconf, srctree)
    settings = collect_settings(kconf, source_cache)

    args.out_build.write_text(_render_build_file(settings), encoding="utf-8")
    args.out_config_h_in.write_text(_render_config_h_in(settings), encoding="utf-8")
    args.out_manifest.write_text(_render_manifest(kconf, srctree), encoding="utf-8")


if __name__ == "__main__":
    main()
