"""A script for parsing kconfig files and rendering the equivalent to a Bazel repository"""

import argparse
import json
import logging
from pathlib import Path, PurePosixPath
from typing import Any, NotRequired, TypedDict

from kconfig.private.kconfig_parser import (
    KconfigSetting,
    collect_settings,
    parse_kconfig,
    read_source_files,
)

_BUILD_HEADER_TEMPLATE = """\
load("@bazel_skylib//rules:common_settings.bzl", {rules})
"""

_FLAG_TEMPLATE = """\
{rule}(
    name = "CONFIG_{name}",
    build_setting_default = {default},
    visibility = ["//visibility:public"],
)
"""

_SETTING_ALIAS_LOAD = """\
load("@rules_kconfig//kconfig/private:kconfig_setting_alias.bzl", "kconfig_setting_alias")
"""

_SETTING_ALIAS_TEMPLATE = """\
kconfig_setting_alias(
    name = "CONFIG_{name}",
    actual = "{label}",
    visibility = ["//visibility:public"],
)
"""

_AUTOCONF_TEMPLATE = """\
load("@rules_kconfig//kconfig/private:kconfig_autoconf.bzl", "kconfig_autoconf")
load("@rules_kconfig//kconfig/private:kconfig_savedefconfig.bzl", "kconfig_savedefconfig")
load("@rules_kconfig//kconfig/private:kconfig_settings_group.bzl", "kconfig_settings_group")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc_autoconf//autoconf:autoconf_hdr.bzl", "autoconf_hdr")

kconfig_settings_group(
    name = "settings",
    settings = [
{settings}
    ],
    visibility = ["//visibility:public"],
)

kconfig_autoconf(
    name = "autoconf",
    settings = [
{settings}
    ],
    visibility = ["//visibility:public"],
)

autoconf_hdr(
    name = "config_h",
    out = "config.h",
    template = "config.h.in",
    deps = [":autoconf"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "config",
    hdrs = ["config.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
)

kconfig_savedefconfig(
    name = "savedefconfig",
    settings = [
{settings}
    ],
    defaults = {{
{defaults}
    }},
    visibility = ["//visibility:public"],
)
"""

_KCONFIG_LIBRARY_TEMPLATE = """\
load("@rules_kconfig//kconfig:kconfig_library.bzl", "kconfig_library")

kconfig_library(
    name = "lib",
    root = "kconfig_srcs/{root}",
    srcs = glob(["kconfig_srcs/**"]),
    visibility = ["//visibility:public"],
)
"""

_MENUCONFIG_TEMPLATE = """\
load("@rules_kconfig//kconfig:menuconfig.bzl", "menuconfig")

menuconfig(
    name = "menuconfig",
    config = "{config_ws_path}",
    kconfig = "//:lib",
    visibility = ["//visibility:public"],
)
"""

_CONFIG_H_IN_TEMPLATE = """\
/* Generated by rules_kconfig. DO NOT EDIT. */

{undefs}
"""

_SETTINGS_BZL_TEMPLATE = """\
\"\"\"Generated by rules_kconfig. DO NOT EDIT.\"\"\"

_BOOL_FLAGS = [
{bool_flags}
]

_OTHER_FLAGS = [
{other_flags}
]

_DEFAULTS = {{
{defaults}
}}

def kconfig_config_settings(name, options = {{}}, visibility = None):
    \"\"\"Generate config_setting targets for kconfig flags.

    Bool flags always produce a config_setting matching ``"true"``.
    Non-bool flags use values from *options*, falling back to their
    Kconfig default when not specified.  Flags with neither are skipped.

    Args:
        name: Prefix for generated target names.  Each target is named
            ``{{name}}.{{CONFIG_*}}``.
        options: Dict mapping ``CONFIG_*`` names to lists of string
            values.  Each value produces a separate ``config_setting``.
        visibility: Visibility for generated targets.
    \"\"\"
    for flag in _BOOL_FLAGS:
        native.config_setting(
            name = name + "." + flag.name,
            flag_values = {{flag: "true"}},
            visibility = visibility,
        )

    for flag in _OTHER_FLAGS:
        values = options.get(flag.name)
        if values == None:
            default = _DEFAULTS.get(flag.name)
            if default == None:
                continue
            values = [default]
        for value in values:
            native.config_setting(
                name = name + "." + flag.name + "_" + str(value),
                flag_values = {{flag: str(value)}},
                visibility = visibility,
            )
"""

_SETTINGS_BUILD_TEMPLATE = """\
# Generated by rules_kconfig. DO NOT EDIT.

load("//:settings.bzl", "kconfig_config_settings")

kconfig_config_settings(
    name = "kconfig",{options}
    visibility = ["//visibility:public"],
)
"""

log = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument(
        "--kconfig", type=Path, required=True, help="The path to the root Kconfig file."
    )
    parser.add_argument(
        "--out_build",
        type=Path,
        required=True,
        help="The output location of the `BUILD.bazel` file.",
    )
    parser.add_argument(
        "--out_manifest",
        type=Path,
        required=True,
        help="The output location of the `kconfig.manifest.json` file.",
    )
    parser.add_argument(
        "--out_config_h_in",
        type=Path,
        required=True,
        help="The output location of the `config.h.in` template file.",
    )
    parser.add_argument(
        "--defaults",
        type=Path,
        default=None,
        help="Optional .config file with explicit symbol values that override Kconfig defaults.",
    )
    parser.add_argument(
        "--out_rendered_config",
        type=Path,
        required=True,
        help="The output location of the rendered .config file.",
    )
    parser.add_argument(
        "--repo_name",
        type=str,
        required=True,
        help="Name of the generated repository (used for the repo-named symlink export).",
    )
    parser.add_argument(
        "--srctree",
        type=Path,
        default=None,
        help="The root of the source tree. Defaults to the parent of --kconfig.",
    )
    parser.add_argument(
        "--config_ws_path",
        type=str,
        default=None,
        help="Workspace-relative path to the .config file. When set, a menuconfig target is generated.",
    )
    parser.add_argument(
        "--out_settings_bzl",
        type=Path,
        required=True,
        help="The output location of the generated settings.bzl file.",
    )
    parser.add_argument(
        "--out_settings_build",
        type=Path,
        required=True,
        help="The output location of the generated settings/BUILD.bazel file.",
    )
    parser.add_argument(
        "--settings_labels",
        type=str,
        default="{}",
        help="JSON-encoded dict mapping CONFIG_* names to label strings for user-provided rules.",
    )
    parser.add_argument(
        "--settings_options",
        type=str,
        default="{}",
        help="JSON-encoded dict mapping CONFIG_* names to lists of string values.",
    )
    parser.add_argument("--verbose", action="store_true", help="Enable verbose logging")

    return parser.parse_args()


def _starlark_default(setting: KconfigSetting) -> str:
    """Format a :class:`KconfigSetting` default as a Starlark literal."""
    val = setting.default
    if isinstance(val, bool):
        return "True" if val else "False"
    if isinstance(val, int):
        return str(val)
    escaped = val.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _default_as_string(setting: KconfigSetting) -> str:
    """Format a :class:`KconfigSetting` default for use in a string_dict value.

    Bools become ``"True"``/``"False"``, ints become their decimal
    representation, and strings are returned as-is (with inner quotes
    and backslashes escaped for Starlark).
    """
    val = setting.default
    if isinstance(val, bool):
        return "True" if val else "False"
    if isinstance(val, int):
        return str(val)
    return val.replace("\\", "\\\\").replace('"', '\\"')


def _render_build_file(  # pylint: disable=too-many-arguments
    settings: list[KconfigSetting],
    *,
    repo_name: str,
    root_file: str,
    settings_labels: dict[str, str] | None = None,
    has_rendered_config: bool = False,
    config_ws_path: str | None = None,
) -> str:
    """Render a BUILD.bazel file with build settings for each Kconfig symbol."""
    if not settings:
        return "# No Kconfig symbols found.\n"

    labels = settings_labels or {}
    parts: list[str] = []

    needed_rules = sorted(
        {s.rule for s in settings if f"CONFIG_{s.name}" not in labels}
    )
    if needed_rules:
        parts.append(
            _BUILD_HEADER_TEMPLATE.format(
                rules=", ".join(f'"{r}"' for r in needed_rules),
            )
        )

    if labels:
        parts.append(_SETTING_ALIAS_LOAD)

    exported = [repo_name, "kconfig.manifest.json"]
    if has_rendered_config:
        exported.append("rendered.config")
    parts.append("")
    joined = ", ".join(f'"{f}"' for f in exported)
    parts.append(f'exports_files(glob(["kconfig_srcs/**"]) + [{joined}])\n')

    for s in settings:
        label = labels.get(f"CONFIG_{s.name}")
        parts.append("")
        if label is not None:
            parts.append(_SETTING_ALIAS_TEMPLATE.format(name=s.name, label=label))
        else:
            parts.append(
                _FLAG_TEMPLATE.format(
                    rule=s.rule,
                    name=s.name,
                    default=_starlark_default(s),
                )
            )

    settings_str = "\n".join(f'        ":CONFIG_{s.name}",' for s in settings)
    defaults_str = "\n".join(
        f'        "CONFIG_{s.name}": "{_default_as_string(s)}",' for s in settings
    )
    parts.append("")
    parts.append(
        _AUTOCONF_TEMPLATE.format(settings=settings_str, defaults=defaults_str)
    )

    parts.append("")
    parts.append(_KCONFIG_LIBRARY_TEMPLATE.format(root=root_file))

    if config_ws_path is not None:
        parts.append("")
        parts.append(_MENUCONFIG_TEMPLATE.format(config_ws_path=config_ws_path))

    return "".join(parts)


def _render_config_h_in(settings: list[KconfigSetting]) -> str:
    """Render a config.h.in template with #undef for each Kconfig symbol."""
    undefs = "\n".join(f"#undef CONFIG_{s.name}" for s in settings)
    return _CONFIG_H_IN_TEMPLATE.format(undefs=undefs)


def _render_settings_bzl(
    settings: list[KconfigSetting],
    *,
    settings_labels: dict[str, str] | None = None,
) -> str:
    """Render a settings.bzl with flag metadata baked into the macro."""
    labels = settings_labels or {}
    flag_settings = [s for s in settings if f"CONFIG_{s.name}" not in labels]

    bool_flags = [s for s in flag_settings if s.rule == "bool_flag"]
    other_flags = [s for s in flag_settings if s.rule != "bool_flag"]

    bool_lines = "\n".join(f'    Label("//:CONFIG_{s.name}"),' for s in bool_flags)
    other_lines = "\n".join(f'    Label("//:CONFIG_{s.name}"),' for s in other_flags)
    default_lines = "\n".join(
        f'    "CONFIG_{s.name}": "{_default_as_string(s)}",' for s in other_flags
    )

    return _SETTINGS_BZL_TEMPLATE.format(
        bool_flags=bool_lines,
        other_flags=other_lines,
        defaults=default_lines,
    )


class KconfigManifest(TypedDict):
    """Manifest describing the Kconfig source tree for a repository rule."""

    root: str
    """Entry-point Kconfig file, relative to srctree."""

    files: list[str]
    """All Kconfig source files (sorted, deduplicated), relative to srctree."""

    config: NotRequired[str]
    """Rendered .config filename. Present only when defaults are provided."""

    settings_labels: NotRequired[dict[str, str]]
    """CONFIG_* names mapped to user-provided label strings."""


def _build_manifest(
    kconf: Any,
    srctree: Path,
    *,
    has_defaults: bool = False,
    settings_labels: dict[str, str] | None = None,
) -> KconfigManifest:
    """Build a manifest with root and files list."""
    files: list[str] = []
    for filename in kconf.kconfig_filenames:
        abs_path = Path(filename)
        if not abs_path.is_absolute():
            abs_path = srctree / filename
        rel = abs_path.absolute().relative_to(srctree.absolute())
        files.append(str(PurePosixPath(rel)))
    manifest = KconfigManifest(root=files[0], files=sorted(set(files)))
    if has_defaults:
        manifest["config"] = "rendered.config"
    if settings_labels:
        manifest["settings_labels"] = settings_labels
    return manifest


def main() -> None:
    """The main entrypoint"""
    args = parse_args()

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO)

    kconfig_path: Path = args.kconfig.absolute()
    srctree: Path = (args.srctree or kconfig_path.parent).absolute()

    log.info("Parsing %s (srctree=%s)", kconfig_path, srctree)

    kconf = parse_kconfig(kconfig_path, srctree)

    log.info(
        "Parsed %d unique symbols from %d files",
        len(kconf.unique_defined_syms),
        len(kconf.kconfig_filenames),
    )

    has_defaults = args.defaults is not None
    if has_defaults:
        defaults_path = args.defaults.absolute()
        log.info("Loading defaults from %s", defaults_path)
        kconf.load_config(str(defaults_path))

    source_cache = read_source_files(kconf, srctree)
    settings_labels: dict[str, str] = json.loads(args.settings_labels)
    settings = collect_settings(
        kconf,
        source_cache,
        has_defaults=has_defaults,
        labeled_symbols=set(settings_labels),
    )

    manifest_data = _build_manifest(
        kconf, srctree, has_defaults=has_defaults, settings_labels=settings_labels
    )
    manifest_json = json.dumps(manifest_data, indent=2) + "\n"

    args.out_build.write_text(
        _render_build_file(
            settings,
            repo_name=args.repo_name,
            root_file=manifest_data["root"],
            settings_labels=settings_labels,
            has_rendered_config=True,
            config_ws_path=args.config_ws_path,
        ),
        encoding="utf-8",
    )
    args.out_config_h_in.write_text(_render_config_h_in(settings), encoding="utf-8")
    args.out_manifest.write_text(manifest_json, encoding="utf-8")

    args.out_settings_bzl.write_text(
        _render_settings_bzl(settings, settings_labels=settings_labels),
        encoding="utf-8",
    )
    args.out_settings_build.parent.mkdir(parents=True, exist_ok=True)

    settings_options: dict[str, list[str]] = json.loads(args.settings_options)
    if settings_options:
        options_lines = "\n".join(
            f'        "{k}": {json.dumps(v)},'
            for k, v in sorted(settings_options.items())
        )
        options_str = f"\n    options = {{\n{options_lines}\n    }},"
    else:
        options_str = ""
    args.out_settings_build.write_text(
        _SETTINGS_BUILD_TEMPLATE.format(options=options_str), encoding="utf-8"
    )

    kconf.write_config(str(args.out_rendered_config))


if __name__ == "__main__":
    main()
